
natural_habitats <- c(
  "Atlantic rainforest",                                                                                                                                       
  "Rainforest",                                                                                                                                              
  "Deciduous primary forest",                                                                                                                                  
  "Primary riparian forest",
  "Fragmented forest",
  "Tropical forest",                                                                                                                                        
  "Primary cloud forest",                                                                                                                                  
  "Secondary and primary lowland rainforest",                                                                                                              
  "Mangrove",                                                                                                                                                
  "Pine rockland",                                                                                                                                        
  "Broadleaved forest",                                                                                                                                       
  "Highly degraded tropical vegetation",                                                                                                                  
  "Degraded tropical vegetation",                                                                                                                             
  "Highly disturbed gallery forest",                                                                                                                     
  "Tropical shrub",                                                                                                                                            
  "Humid tropical forests",                                                                                                                                   
  "Evergreen Mixed Rainforest",                                                                                                                                
  "Upland deciduous forest",                                                                                                                                  
  "Oak-Hornbean forest",                                                                                                                                      
  "Grassland and Baccharis-Lupin cover",                                                                                                                      
  "Baccharis-grassland",                                                                                                                                      
  "Tropical montane forest (Elevation = 2743 m)",                                                                                                              
  "Tropical montane forest (Elevation = 3048 m)",                                                                                                             
  "Tropical montane forest (Elevation = 2896 m)",                                                                                                           
  "Tropical montane forest (Elevation = 2591 m)",                                                                                                              
  "Tropical montane forest (Elevation = 3200 m)",                                                                                                              
  "Tropical montane forest (Elevation = 2438 m)",                                                                                                             
  "Old-growth forest",                                                                                                                                         
  "Closed canopy old growth forest and forest regenerating from timber",                                                                                       
  "Old-growth forest and regenerating forest",                                                                                                               
  "Second-growth, mixed deciduous forest dominated by Rhododendron spp. in the riparian zone",
  "Deciduous litter level topography; Oak-pine-aspen forest floor",                                                                                            
  "Beech-maple forest floor",                                                                                                                                 
  "Deciduous litter depressions; Oak-pine-aspen forest floor",                                                                                               
  "Woodland",                                                                                                                                                  
  "Mesic forest",                                                                                                                                              
  "Hemlock and mixed deciduous forest",
  "Talus habitat",                                                                                                                                             
  "Spruce forest",                                                                                                                                             
  "Mature wood (Fir, Beech, Spruce)",                                                                                                                          
  "Mediterranean oak-woodland",                                                                                                                              
  "Alpine grassland",                                                                                                                                          
  "Deciduous forest dominated by introduced plant species",                                                                                                    
  "Acacia tortilis riverine woodland",                                                                                                                         
  "Outcrops",                                                                                                                                                  
  "Lava desert",                                                                                                                                               
  "Acacia nubica alluvial flat",                                                                                                                               
  "Barren dunes",                                                                                                                                              
  "Mostly shrubs; scattered tree saplings; herb layer dominated by Mana grass (Cymbopogon confertifloru)",
  "Gorse (Ulex euopaeus)dominat- ing; scattered cypress trees (Cupressusmacrocarpus)h;erb layer of grass and Aristeaeckloni (Iridaceae)",
  "Rocky hills",                                                                                                                                               
  "Banksia woodland",                                                                                                                                          
  "Gravel plains",                                                                                                                                            
  "Clay plains",                                                                                                                                              
  "Sand dunes",                                                                                                                                                
  "Grassland",                                                                                                                                                 
  "Stabilized dunes",                                                                                                                                          
  "Sand plains",                                                                                                                                               
  "Limestone karstic island dominated by xerophytic vegetation",                                                                                               
  "Forest",                                                                                                                                                   
  "Beach",                                                                                                                                                    
  "Playa",                                                                                                                                                     
  "Bahada",                                                                                                                                                    
  "Tropical Deciduous Forest",                                                                                                                                 
  "Desert",                                                                                                                                                    
  "High forest",                                                                                                                                              
  "Palm forest",                                                                                                                                               
  "Sea-bird",                                                                                                                                                  
  "Degraded",                                                                                                                                                  
  "Mixed forest",                                                                                                                                              
  "Moss forest",                                                                                                                                               
  "Coastal",                                                                                                                                                   
  "Lowland",                                                                                                                                                   
  "Mid forest",                                                                                                                                                
  "Atlantic Forest",                                                                                                                                           
  "Cordia gharaf",                                                                                                                                             
  "Salvadora persica alluvial flat",                                                                                                                           
  "Mix scrub",
  "Bracken",                                                                                                                                                  
  "Litter habitat",                                                                                                                                            
  "Gravel pit with woodland and meadows",                                                                                                                      
  "Magueal",                                                                                                                                                   
  "Pine Oak woodland",                                                                                                                                         
  "Casuarina",                                                                                                                                                 
  "Mangrove forest",                                                                                                                                           
  "Field abandoned since 53 years",                                                                                                                            
  "Field abandoned since 40 years",                                                                                                                            
  "Field abandoned since 30 years",                                                                                                                            
  "Field abandoned since 42 years",                                                                                                                            
  "Field abandoned since 12 years",                                                                                                                            
  "Field abandoned since 60 years",                                                                                                                            
  "Field abandoned since 41 years",                                                                                                                            
  "Scrub",                                                                                                                                                     
  "Rock habitat",                                                                                                                                              
  "Subalpine grasslands with dwarf shrubs",                                                                                                                    
  "Forest (Logged)",                                                                                                                                           
  "Tropical rainforest",                                                                                                                                       
  "Nothofagus obliqua forest",                                                                                                                                 
  "Nothofagus obliqua & N. pumilio Forest",                                                                                                                    
  "Mature foodplain Forest",                                                                                                                                   
  "Deciduous Forest",                                                                                                                                          
  "Coppices",                                                                                                                                                  
  "Woodland dominated by Oak, but considerable amount of ash and birch",                                                                                       
  "Oakwood",                                                                                                                                                   
  "Wet forest",                                                                                                                                                
  "Moist forest",                                                                                                                                              
  "ash-alder forest",                                                                                                                                          
  "Semi-desert - Steppe",                                                                                                                                      
  "oak-hornbeam-lime forest",                                                                                                                                  
  "Woodland predominantly birch with oak and some ash, rowan, holly, bird-cherry ",                                                                            
  "Woodland mainly oak, with birch and hazel, on a steep slope",                                                                                               
  "Prairie",                                                                                                                                                   
  "Saltmarsh",                                                                                                                                                 
  "Coastal sage scrub",                                                                                                                                        
  "Coastal sage scrub (Burned)",                                                                                                                               
  "Tundra",                                                                                                                                                    
  "Forest fragments",                                                                                                                                          
  "Austrocedrus chilensis & Nothofagus obliqua forest",                                                                                                        
  "Beech (pumilio-no bamboo) forest",                                                                                                                          
  "Reed beds of Phragmitetum communis",                                                                                                                        
  "Arid area",                                                                                                                                                 
  "Reed beds of Phalaridetum arundinacene and Glycerietum maximae",                                                                                            
  "Water surface",                                                                                                                                             
  "Peat bog",                                                                                                                                                  
  "Seasonally flooded Forest",                                                                                                                                 
  "Upland Forest",                                                                                                                                             
  "alder-swamp forest",                                                                                                                                        
  "Rain Forest (Logged 1-2 years)",                                                                                                                            
  "Rain Forest (Logged 8-12 years)",                                                                                                                           
  "Rain Forest",                                                                                                                                               
  "Semideciduous scrub",                                                                                                                                       
  "Nothofagus antartica tall scrub",                                                                                                                           
  "Nothofagus antartica low scrub",                                                                                                                            
  "Chusquea argentina forest",                                                                                                                                 
  "Evergreen Temperate Forest (Aspen flatland)",                                                                                                               
  "Deciduous Temperate Forest (Willow-Sedge swamp)",                                                                                                           
  "Deciduous Temperate Forest (Scrub-meadow)",                                                                                                                 
  "Beech (antarctica-dombeyi-bamboo) forest",                                                                                                                  
  "Scrub-beech",                                                                                                                                               
  "Dense cedar forest",                                                                                                                                        
  "Beech (pumilio-dombeyi-bamboo) forest",                                                                                                                     
  "Scrub-sedge",                                                                                                                                               
  "Dense beech (dombeyi-bamboo) forest",                                                                                                                       
  "Primary Forest",                                                                                                                                            
  "Secondary Forest",                                                                                                                                          
  "Unlogged forest >300 m",                                                                                                                                    
  "Logged forest <180m",                                                                                                                                       
  "Unlogged forest <180 m",                                                                                                                                    
  "Logged forest >300 m",                                                                                                                                      
  "Lowland dipterocarp forest",                                                                                                                                
  "Logged forest",                                                                                                                                             
  "Unlogged forest",                                                                                                                                           
  "Lowland Forest",                                                                                                                                            
  "Dry forest",                                                                                                                                                
  "Steppe",                                                                                                                                                    
  "Deciduous Broad-Leaved Forest",                                                                                                                             
  "Open woodland",                                                                                                                                             
  "Poaceae steppe",                                                                                                                                            
  "Herbaceous grassland",                                                                                                                                      
  "Sandy",                                                                                                                                                     
  "Swamp",                                                                                                                                                     
  "Woodland, predominantly oak, with birch, some rowan, ash, holly, bird-cherry etc. and dense hazel thickets, all heavily coppiced",
  "Woodland with well grown and well spaced oaks on the hill slope in the northern half",
  "Secondary habitat (including plantations, secondary scrub and small isolated blocks of disturbed forest)",
  "Hawthorn",                                                                                                                                                  
  "Wood",
  "Beech forest",                                                                                                                                              
  "Coniferous forest",                                                                                                                                         
  "Chalk grassland shrub",                                                                                                                                     
  "Mixed Forest",                                                                                                                                              
  "Open areas",                                                                                                                                                
  "Tropical forest (Burnt)",                                                                                                                                   
  "Mainly re-growth Forest (315 m alt)",                                                                                                                       
  "Mainly old-growth Forest (185 m alt",                                                                                                                       
  "Old-growth Forest (160 m alt)",
  "Sapling mahogany <6 yrs (219 m alt)",                                                                                                                       
  "Mature mahogany c. 40-year-old (230-235 m alt)",                                                                                                            
  "Upland Forest (820-870 m alt)",                                                                                                                             
  "Semi-nature mahogany c. 25-year-old (185 m alt)",                                                                                                           
  "Re-growth Forest and old-growth Forest (210-455 m alt)",                                                                                                    
  "Old-growth Forest (360 m alt)",                                                                                                                             
  "Re-growth Forest with Merremia vine (70 m alt)",                                                                                                            
  "Old-growth Forest (195 m alt)",                                                                                                                             
  "Submontane shrubland on the slopes and cliffs of the granite mountains (c380-750 m)",
  "Open and woody-based herb communities on the limestone plateau (c 500-720 m)",
  "Dwarf coastal vegetation: mosaic of low succulent shrubs and woody-based herbs, variously dominated by Limonium, Zygophyllum, Suaeda and Pulicaria (<50 m)",
  "Succulent shrubland on limestone cliffs and slopes (0-550 m)",
  "Semi-evergreen woodland of limestone escarpments and sheltered ravines (mostly c 500-700 m)",
  "Croton shrubland on the coastal plains (mostly <50 m)",
  "Montane mosaic of shrubland woodland and grassland in the granite mountains (> 750 m)",
  "Juniper",
  "Forest edge",                                                                                                                                               
  "Natural forest",                                                                                                                                            
  "Mountain",                                                                                                                                                  
  "Gallery forest",                                                                                                                                            
  "Savanna",                                                                                                                                                   
  "Foodplain",                                                                                                                                                 
  "Cerrado",                                                                                                                                                   
  "Ruin site in the forest",                                                                                                                                   
  "Tropical semi-deciduous forest",                                                                                                                            
  "Mountain Rain Forest",                                                                                                                                      
  "Sparse vegetation-Upper elevation",                                                                                                                         
  "Dense vegetation-Lower elevation",                                                                                                                          
  "Dense vegetation-Upper elevation",                                                                                                                          
  "Sparse vegetation-Lower elevation",                                                                                                                         
  "Sparse cedar forest",                                                                                                                                      
  "Matorral",                                                                                                                                                  
  "Tropical Forest",                                                                                                                                           
  "Tropical evergreen Forest",                                                                                                                                 
  "Dry evergreen Forest",                                                                                                                                      
  "Scotts pine",                                                                                                                                               
  "Native pinewood",                                                                                                                                           
  "Reed",                                                                                                                                                      
  "Arid with little shrub cover",                                                                                                                              
  "Pinewood",                                                                                                                                                  
  "Tropical forest (Unburnt)",                                                                                                                                 
  "<65% Forest cover",                                                                                                                                        
  ">65% Forest cover",                                                                                                                                         
  "Pine forest",                                                                                                                                               
  "Pine forest (Control site)",                                                                                                                                
  "Pine forest (High retention thinning)",                                                                                                                     
  "Pine forest (Low retention thinning)",                                                                                                                      
  "Evergreen Temperate Forest (Lodgepole pine)",                                                                                                               
  "Evergreen Temperate Forest (Lodgepole-Spruce-Fir)",                                                                                                         
  "Evergreen Temperate Forest (Spruce-Fir)",                                                                                                                   
  "Nothofagus pumilio forest",                                                                                                                                 
  "Hypersaline tidal marsh",                                                                                                                                   
  "Marsh",                                                                                                                                                     
  "Beech (dombeyi-no bamboo) forest",                                                                                                                          
  "Undisturbed",                                                                                                                                               
  "Boreal forest (Undisturbed)",                                                                                                                               
  "Boreal forest (Disturbed)",                                                                                                                                 
  "Cactus grassland",                                                                                                                                          
  "Bunchgrass grassland",                                                                                                                                      
  "Dry forest (Undisturbed)",                                                                                                                                  
  "Secondary forest",                                                                                                                                          
  "Plantation",                                                                                                                                                
  "Semi-natural area",                                                                                                                                         
  "Beech (dombeyi-no bamboo) Forest",                                                                                                                          
  "Primary Forest (Steep slopes)",                                                                                                                             
  "Forest (Logged recently)",                                                                                                                                  
  "Primary Forest (Ondulating)",                                                                                                                               
  "Forest (Logged old)",                                                                                                                                       
  "Dry deciduous forest",                                                                                                                                      
  "Moist deciduous forest",                                                                                                                                    
  "Foodplain Forest",                                                                                                                                          
  "Coastal and interior dry forests, shrublands, and wetlands",                                                                                                
  "Lowland Rainforest",                                                                                                                                        
  "Hills",                                                                                                                                                     
  "Makatea",                                                                                                                                                   
  "Boreal forest",                                                                                                                                             
  "Closed habitat",                                                                                                                                            
  "Open habitat",                                                                                                                                              
  "Atlantic Rainforest",                                                                                                                                       
  "Floodplain",                                                                                                                                                
  "Primary and mixed forest",                                                                                                                                  
  "Grassland and Tropical forest",                                                                                                                             
  "Taiga",                                                                                                                                                     
  "Lowland to upland Tundra",                                                                                                                                  
  "Coastal Forest",                                                                                                                                            
  "Upland Tundra",                                                                                                                                             
  "Coastal Forest to upland Tundra",                                                                                                                           
  "Mountain arid habitat",                                                                                                                                     
  "Flat arid area",                                                                                                                                            
  "Forest and Wooded grassland",                                                                                                                               
  "Riverine forest outside National Park",                                                                                                                     
  "Riverine forest in National Park",                                                                                                                          
  "Shorea forest outside National Park",                                                                                                                       
  "Shorea forest in National Park",                                                                                                                            
  "Open wet savannah",                                                                                                                                         
  "Temperate forest",                                                                                                                                          
  "Mixed habitat (Fir and Pine forest, and Broadleave forest)",                                                                                                
  "Semi-deciduous tropical forest",                                                                                                                            
  "Forest land and small, private inholdings of open and edge habitat",                                                                                        
  "Lowland dipterocarp rain forest",                                                                                                                           
  "Mediterranean woodland",                                                                                                                                    
  "Semi-arid",                                                                                                                                                 
  "Sub-alpine",                                                                                                                                                
  "Lowland foodplain Forest",                                                                                                                                  
  "Premontane humid forest",                                                                                                                                   
  "Llanos",                                                                                                                                                    
  "Mixture of bog and scrub",                                                                                                                                  
  "Machair grassland",                                                                                                                                         
  "Mediterranean scrubland",                                                                                                                                   
  "Ash stand",                                                                                                                                                 
  "Primary rainforest",                                                                                                                                        
  "Mixed semi- evergreen/coniferous, upper montane, dry evergreen and wet evergreen forests",
  "Woodland, Shrubland, Grassland",                                                                                                                            
  "Tropical wet forest",                                                                                                                                       
  "Secondary tropical forest",                                                                                                                                 
  "Primary tropical forest",                                                                                                                                   
  "Brazilian pantanal",                                                                                                                                        
  "Grassland (Burned)",                                                                                                                                        
  "Sedge-shrub community on coastal dunes",                                                                                                                    
  "Mature beech habitat",                                                                                                                                      
  "Mixed habitat (Norway spruce, pole-stage beech, elder)",                                                                                                    
  "Pole-stage beech",                                                                                                                                          
  "Coastal plain",                                                                                                                                             
  "Perennial and annual grasses",                                                                                                                              
  "Vegetation dominated by shrubs, bushes, scattered trees and perennial grass",                                                                               
  "Stream deciduous forest",                                                                                                                                   
  "Riverine forest"
)
